name: Power BI Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Power BI CLI
        run: npm install -g powerbi-cli

      - name: Print PATH
        run: echo $PATH

      - name: Update Power BI
        run: |
          # Replace /usr/local/bin/pbi with the actual full path to pbi from npm bin -g
          /usr/local/bin/pbi -u "$TECH_BI_DEV_EMAIL" -p "$Wah71567" -f path/to/your/powerbi/file.pbix
        env:
          TECH_BI_DEV_EMAIL: ${{ secrets.tech_bi_dev_email }}
          Wah71567: ${{ secrets.Wah71567 }}
